config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :challenges, only: [:index, :show, :destroy] do
    resources :chats, only: [:index, :create]
  end

  resources :chats, only: :show do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :chats, dependent: :destroy
  validates :name, :module, :content, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :challenge
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  validates :content, length: { minimum: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = Challenge.all
    # render 'index.html.erb'
    respond_to do |format| # format => html,json,txt
      format.html { render 'index' }
      format.json { render json: @challenges }
    end
  end

  def show
    @challenge = Challenge.find(params[:id])
    @chats = @challenge.chats.where(user: current_user)
    respond_to do |format| # format => html,json,txt
      format.html { render 'show' }
      format.json { render json: @challenge }
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    @challenge = Challenge.find(params[:challenge_id])

    @chat = Chat.new(title: "Untitled")
    @chat.challenge = @challenge
    @chat.user = current_user

    if @chat.save
      redirect_to chat_path(@chat)
    else
      @chats = @challenge.chats.where(user: current_user)
      render "challenges/show"
    end
  end

  def show
    @chat = Chat.find(params[:id])
    @challenge = @chat.challenge
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    SYSTEM_PROMPT = <<-PROMPT
      You are an experienced programming teacher.
      I am a student at the Le Wagon AI Software Development bootcamp, learning how to code.
      Help me break down my problem into small, actionable steps, without giving any code at all.
      Provide step-by-step advice in Markdown.
    PROMPT

  def create
    @chat = current_user.chats.find(params[:chat_id])
    @challenge = @chat.challenge

    @message = Message.new(message_params)
    @message.chat = @chat
    @message.role = "user"

    # 1. Create the user's message
    if @message.save
      response = chat_response
      # 5. Create the assistant's message
      Message.create(role: 'assistant', chat: @chat, content: response.content)
      # redirect_to chat_path(@chat)
      # we want to just send the HTML for those last two messages "over the wire"
      respond_to do |format| # format => html,json,txt
        format.html { redirect_to chat_path(@chat) }
        format.turbo_stream # render 'create.turbo_stream.erb'
      end
    else
      respond_to do |format|
        format.html { render "chats/show", status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("new_message", partial: "messages/form", locals: { chat: @chat, message: @message })
        end
      end
    end
  end

  private

  def chat_response
    # 2. Create the RubyLLM chat
    @ruby_llm = RubyLLM.chat
    # 3. Add the previous conversation to the chat
    @chat.messages.each do |message|
      @ruby_llm.add_message(message)
    end
    # 3a. Give a summary of the conversation instead
    # 4. Give the tool to the llm (in case it needs it)
    @ruby_llm.with_tool(CreateChallengeTool.new)
    # 5. Give the system prompt and context to the chat
    @ruby_llm.with_instructions("#{SYSTEM_PROMPT}\n#{challenge_context}")
    # 6. Ask the question of the user
    return @ruby_llm.ask(@message.content)
  end

  def challenge_context
    "Here is the context of the challenge: #{@challenge.content}."
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @challenges = Challenge.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    Kramdown::Document.new(text, input: 'GFM', syntax_highlighter: "rouge").to_html
  end
end

app/views/challenges/index.html.erb
<h1>Challenges</h1>
<ul>
  <% @challenges.each do |challenge| %>
    <li><%= link_to challenge.name, challenge_path(challenge) %></li>
  <% end %>
</ul>

app/views/challenges/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to 'Challenges', challenges_path  %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @challenge.name %></li>
    </ol>
  </nav>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to 'All Chats', "#offcanvasExample", data: { bs_toggle: 'offcanvas' }, role: "button"  %>
      </li>
      <li class="breadcrumb-item"><%= link_to 'New Chat', challenge_chats_path(@challenge), data: { turbo_method: :post }  %></li>
    </ol>
  </nav>
</div>
<h1><%= @challenge.name %></h1>
<%= raw(render_markdown(@challenge.content)) %>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Chats</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      <% if @challenge.chats.any? %>
        <% @challenge.chats.each do |chat| %>
          <li>
            <%= link_to chat.title, chat_path(chat)  %>
          </li>
        <% end %>
      <% else %>
        <li>No chats yet. <%= link_to 'Create one.', challenge_chats_path(@challenge), data: { turbo_method: :post }  %></li>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to @chat.challenge.name, challenge_path(@chat.challenge)  %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @chat.title %></li>
    </ol>
  </nav>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to 'All Chats', challenges_path  %></li>
      <li class="breadcrumb-item"><%= link_to 'New Chat', challenge_chats_path(@challenge), data: { turbo_method: :post }  %></li>
    </ol>
  </nav>
</div>
<div id="chat_title">
  <h1><%= @chat.title %></h1>
</div>
<%# We don't want to use @instance_var inside of partials %>
<div id="messages">
  <%= render 'messages/messages', messages: @chat.messages.order(:created_at) %>
  <%# inside of the 'messages' partial, i have access to a 'messages' variable %>
</div>
<div id="new_message">
  <%= render "messages/form", chat: @chat, message: @message %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAiChallenges</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container my-4">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for [chat, message], html: { data: { controller: 'spin '}} do |f| %>
  <%= f.input :content, placeholder: "Ask a question", required: true, label: false %>
  <%= f.button :submit, 'Ask LLM', class: 'btn btn-primary', data: { action: 'click->spin#start'} %>
<% end %>

app/views/messages/_messages.html.erb
<% messages.each do |message| %>
  <% if message.role == "user" %>
    <div class="d-flex justify-content-end mb-2" data-controller="auto-scroll">
      <div class="bg-white px-3 pb-0 pt-3 rounded-pill">
        <%= raw(render_markdown(message.content)) %>
      </div>
    </div>
  <% elsif message.role == "assistant" %>
    <div class="d-flex justify-content-start mb-5">
      <div class="px-3 pb-0 pt-3">
        <%= raw(render_markdown(message.content)) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "messages" do %>
  <%= render "messages/messages", messages: @chat.messages.order(:created_at).last(2) %>
<% end %>
<%= turbo_stream.update "new_message" do %>
  <%= render "messages/form", chat: @chat, message: Message.new %>
<% end %>

app/views/pages/home.html.erb
<h1>Challenges</h1>
<ul>
  <% @challenges.each do |challenge| %>
    <li><%= link_to challenge.name, challenge_path(challenge) %></li>
  <% end %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Challenges", challenges_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://media.printables.com/media/prints/744872/images/5815268_a3bff0c6-4b08-4082-83ff-e773b4aec2ad_f82d2ae9-4bba-4dc6-86a5-7f7b4f98e48a/thumbs/inside/1280x960/png/rick-roll-2.webp", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Challenges", challenges_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>